const translations = {
  uz: {
    newsTitle: "Yangiliklar",
    newsDescription: "Eng so‘nggi yangiliklar va voqealar bilan tanishing.",
    showMore: "Yana ko'rsatish",
    hide: "Yopish",
    enterNameAndSurname: "Ismingiz va familiyangizni kiriting",
    namePlaceholder: "Ism",
    surnamePlaceholder: "Familiya",
    leaveFeedback: "Fikr-mulohazalar qoldiring",
    writeYourFeedback: "Fikringizni yozing...",
    submit: "Jo‘natish",
    backButton: "Ortga",
    allNews: [
      {
        id: 1,
        title: "Yangi klinika ochildi!",
        description: "Bizning yangi klinikamiz ochilishi munosabati bilan barcha xizmatlar uchun chegirmalar mavjud.",
        image: require('../images/news1.jpg'), // tasvirlar faylga mos ravishda
        category: "Sog'liqni saqlash",
        date: "2024-11-20",
      },
      {
        id: 2,
        title: "Yilning eng yaxshi shifokori tanlandi!",
        description: "Dr. Karimov yilning eng yaxshi shifokori unvoniga sazovor bo'ldi.",
        image: require('../images/news2.jpg'),
        category: "Yangiliklar",
        date: "2024-11-18",
      },
      {
        id: 3,
        title: "Yangi mobil ilova ishlab chiqildi",
        description: "Yangi mobil ilovamiz foydalanuvchilar uchun qulaylik yaratadi.",
        image: require('../images/news1.jpg'),
        category: "Texnologiya",
        date: "2024-11-25",
      },
    ],
  },

  ru: {
    newsTitle: "Новости",
    newsDescription: "Ознакомьтесь с последними новостями и событиями.",
    showMore: "Показать больше",
    hide: "Скрыть",
    enterNameAndSurname: "Введите ваше имя и фамилию",
    namePlaceholder: "Имя",
    surnamePlaceholder: "Фамилия",
    leaveFeedback: "Оставьте ваш отзыв",
    writeYourFeedback: "Напишите ваш отзыв...",
    submit: "Отправить",
    backButton: "Назад",

    allNews: [
      {
        id: 1,
        title: "Открылась новая клиника!",
        description: "В связи с открытием нашей новой клиники действуют скидки на все услуги.",
        image: require('../images/news1.jpg'),
        category: "Здравоохранение",
        date: "2024-11-20",
      },
      {
        id: 2,
        title: "Доктор года выбран!",
        description: "Доктор Каримов удостоен титула Доктора года.",
        image: require('../images/news2.jpg'),
        category: "Новости",
        date: "2024-11-18",
      },
      {
        id: 3,
        title: "Разработано новое мобильное приложение",
        description: "Наше новое мобильное приложение создает удобства для пользователей.",
        image: require('../images/news1.jpg'),
        category: "Технологии",
        date: "2024-11-25",
      },
    ],
  },

  en: {
    newsTitle: "News",
    newsDescription: "Stay updated with the latest news and events.",
    showMore: "Show More",
    hide: "Hide",
    enterNameAndSurname: "Enter your name and surname",
    namePlaceholder: "Name",
    surnamePlaceholder: "Surname",
    leaveFeedback: "Leave your feedback",
    writeYourFeedback: "Write your feedback...",
    submit: "Submit",
    backButton: "Back",

    allNews: [
      {
        id: 1,
        title: "A new clinic has opened!",
        description: "Our new clinic offers discounts on all services during the opening period.",
        image: require('../images/news1.jpg'),
        category: "Healthcare",
        date: "2024-11-20",
      },
      {
        id: 2,
        title: "Doctor of the Year Announced!",
        description: "Dr. Karimov has been named Doctor of the Year.",
        image: require('../images/news2.jpg'),
        category: "News",
        date: "2024-11-18",
      },
      {
        id: 3,
        title: "New mobile app developed",
        description: "Our new mobile app provides convenience for users.",
        image: require('../images/news1.jpg'),
        category: "Technology",
        date: "2024-11-25",
      },
    ],
  },
};

export default translations;
