const translations = {
    uz: {
      title: "Online Qabulga Yozilish",
      description: "Quyidagi formani to‘ldirib, online qabulga yozilishingiz mumkin",
      form: {
        fullName: "To'liq Ismingiz",
        fullNamePlaceholder: "Ismingiz va familiyangiz",
        email: "Email",
        emailPlaceholder: "Emailingizni kiriting",
        phone: "Telefon Raqam",
        phonePlaceholder: "+998 XX XXX XX XX",
        date: "Sana",
        time: "Vaqt",
        services:"Xizmatlar",
        message: "Kasallik tavsifi",
        messagePlaceholder: "Qisqacha izohingiz (ixtiyoriy)",
        submit: "Yozilish",
        success: "Siz muvaffaqiyatli yozildingiz! Biz tez orada siz bilan bog'lanamiz.",
      },
    },
    ru: {
      title: "Запись на Онлайн Прием",
      description: "Вы можете записаться на онлайн прием, заполнив эту форму",
      form: {
        fullName: "Ваше Полное Имя",
        fullNamePlaceholder: "Введите ваше имя и фамилию",
        email: "Эл. почта",
        emailPlaceholder: "Введите ваш email",
        phone: "Номер телефона",
        phonePlaceholder: "+998 XX XXX XX XX",
        date: "Дата",
        time: "Время",
        services:"Услуги",
        message: "Описание заболевания",
        messagePlaceholder: "Краткий комментарий (по желанию)",
        submit: "Записаться",
        success: "Вы успешно записались! Мы скоро свяжемся с вами.",
      },
    },
    en: {
      title: "Online Appointment Booking",
      description: "Fill out the form below to book an online appointment",
      form: {
        fullName: "Full Name",
        fullNamePlaceholder: "Enter your full name",
        email: "Email",
        emailPlaceholder: "Enter your email",
        phone: "Phone Number",
        phonePlaceholder: "+998 XX XXX XX XX",
        date: "Date",
        time: "Time",
        services:"Services",
        message: "Description of the disease",
        messagePlaceholder: "Brief comment (optional)",
        submit: "Submit",
        success: "You have successfully booked! We will contact you shortly.",
      },
    },
  };
  
  export default translations;
  