const translations = {
    uz: {
      signUp: {
        title: "Ro'yxatdan o'tish",
        description: "Hozir ro'yxatdan o'ting va xizmatlardan foydalanishni boshlang!",
        fullNameLabel: "To'liq ism",
        fullNamePlaceholder: "Ismingiz va familiyangiz",
        emailLabel: "Email",
        emailPlaceholder: "Emailingizni kiriting",
        phoneLabel: "Telefon",
        phonePlaceholder: "+998 XX XXX XX XX",
        passwordLabel: "Parol",
        passwordPlaceholder: "Parol kiriting",
        confirmPasswordLabel: "Parolni tasdiqlang",
        confirmPasswordPlaceholder: "Parolni qayta kiriting",
        button: "Ro'yxatdan o'tish",
        passwordMismatch: "Parollar mos kelmadi!",
        loginPrompt: "Allaqachon akkauntingiz bormi?",
        loginLink: "Kirish",
      },
    },
    ru: {
      signUp: {
        title: "Регистрация",
        description: "Зарегистрируйтесь сейчас и начните пользоваться услугами!",
        fullNameLabel: "Полное имя",
        fullNamePlaceholder: "Введите ваше имя и фамилию",
        emailLabel: "Эл. почта",
        emailPlaceholder: "Введите вашу почту",
        phoneLabel: "Телефон",
        phonePlaceholder: "+998 XX XXX XX XX",
        passwordLabel: "Пароль",
        passwordPlaceholder: "Введите пароль",
        confirmPasswordLabel: "Подтвердите пароль",
        confirmPasswordPlaceholder: "Введите пароль ещё раз",
        button: "Регистрация",
        passwordMismatch: "Пароли не совпадают!",
        loginPrompt: "Уже есть аккаунт?",
        loginLink: "Войти",
      },
    },
    en: {
      signUp: {
        title: "Sign Up",
        description: "Sign up now and start using our services!",
        fullNameLabel: "Full Name",
        fullNamePlaceholder: "Enter your full name",
        emailLabel: "Email",
        emailPlaceholder: "Enter your email",
        phoneLabel: "Phone",
        phonePlaceholder: "+998 XX XXX XX XX",
        passwordLabel: "Password",
        passwordPlaceholder: "Enter your password",
        confirmPasswordLabel: "Confirm Password",
        confirmPasswordPlaceholder: "Re-enter your password",
        button: "Sign Up",
        passwordMismatch: "Passwords do not match!",
        loginPrompt: "Already have an account?",
        loginLink: "Login",
      },
    },
  };
  
  export default translations;
  